In [30]:
import pandas as pd
import numpy as numpy
import json
import gzip

pd.set_option("display.max_columns", None)

In [31]:
# Chicago Food Inspections

food_url = (
    "https://data.cityofchicago.org/resource/"
    "4ijn-s7e5.csv?$limit=50000"
)

food_inspections = pd.read_csv(food_url)

print("Shape:", food_inspections.shape)

display(food_inspections.head())

print("\nColumn types:")
print(food_inspections.dtypes)

Shape: (50000, 17)

,inspection_id,dba_name,aka_name,license_,facility_type,risk,address,city,state,zip,inspection_date,inspection_type,results,violations,latitude,longitude,location
0,2643334,KAROLINKA CLUB,KAROLINKA CLUB,1645224.0,Restaurant,Risk 1 (High),6102 S CENTRAL AVE,CHICAGO,IL,60638.0,2026-09-25T00:00:00.000,Non-Inspection,No Entry,NaN,41.781570,-87.762013,"\n, \n(41.78156970293239, -87.76201319891189)"
1,2643326,LITTLE TYKES II DAYCARE INC,LITTLE TYKES II DAYCARE INC,2215776.0,Daycare Above and Under 2 Years,Risk 1 (High),1723 W 35TH ST,CHICAGO,IL,60609.0,2026-09-25T00:00:00.000,Canvass,Pass,"48. WAREWASHING FACILITIES: INSTALLED, MAINTAI...",41.830353,-87.668943,"\n, \n(41.83035319104033, -87.66894292273008)"
2,2643349,BUNDOO KHAN,BUNDOO KHAN,2802568.0,Restaurant,Risk 1 (High),2537-2539 W DEVON AVE,CHICAGO,IL,60659.0,2026-09-25T00:00:00.000,Complaint Re-Inspection,Fail,"28. TOXIC SUBSTANCES PROPERLY IDENTIFIED, STOR...",41.997554,-87.693770,"\n, \n(41.99755417277127, -87.69377017915909)"
3,2643342,CHICAGO PIT STOP BBQ,CHICAGO PIT STOP BBQ,1696182.0,Restaurant,Risk 1 (High),6514 S WESTERN AVE,CHICAGO,IL,60636.0,2026-09-25T00:00:00.000,Complaint Re-Inspection,Pass,NaN,41.775112,-87.683679,"\n, \n(41.77511152013113, -87.68367904074279)"
4,2643336,BACCI CAFE AND PIZZERIA ON MILWAUKEE AVE. INC.,LEGACY PIZZA/BACCI CAFE AND PIZZERIA,1444299.0,Restaurant,Risk 1 (High),4367 N MILWAUKEE AVE,CHICAGO,IL,60641.0,2026-09-25T00:00:00.000,Complaint Re-Inspection,Pass w/ Conditions,63. REMOVAL OF SUSPENSION SIGN - Comments: 'LI...,41.960551,-87.754231,"\n, \n(41.96055088007665, -87.7542307472157)"

Column types:
inspection_id        int64
dba_name            object
aka_name            object
license_           float64
facility_type       object
risk                object
address             object
city                object
state               object
zip                float64
inspection_date     object
inspection_type     object
results             object
violations          object
latitude           float64
longitude          float64
location            object
dtype: object

In [32]:
food_columns = [
    "dba_name",
    "license_",
    "facility_type",
    "address",
    "inspection_date",
    "results",
    "violations",
    "latitude",
    "longitude"
]

display(food_inspections[food_columns].head())

,dba_name,license_,facility_type,address,inspection_date,results,violations,latitude,longitude
0,KAROLINKA CLUB,1645224.0,Restaurant,6102 S CENTRAL AVE,2026-09-25T00:00:00.000,No Entry,NaN,41.781570,-87.762013
1,LITTLE TYKES II DAYCARE INC,2215776.0,Daycare Above and Under 2 Years,1723 W 35TH ST,2026-09-25T00:00:00.000,Pass,"48. WAREWASHING FACILITIES: INSTALLED, MAINTAI...",41.830353,-87.668943
2,BUNDOO KHAN,2802568.0,Restaurant,2537-2539 W DEVON AVE,2026-09-25T00:00:00.000,Fail,"28. TOXIC SUBSTANCES PROPERLY IDENTIFIED, STOR...",41.997554,-87.693770
3,CHICAGO PIT STOP BBQ,1696182.0,Restaurant,6514 S WESTERN AVE,2026-09-25T00:00:00.000,Pass,NaN,41.775112,-87.683679
4,BACCI CAFE AND PIZZERIA ON MILWAUKEE AVE. INC.,1444299.0,Restaurant,4367 N MILWAUKEE AVE,2026-09-25T00:00:00.000,Pass w/ Conditions,63. REMOVAL OF SUSPENSION SIGN - Comments: 'LI...,41.960551,-87.754231

Chicago Business Licenses

In [33]:
# Chicago Business Licenses

license_url = (
    "https://data.cityofchicago.org/resource/"
    "r5kz-chrr.csv?$limit=50000"
)

business_licenses = pd.read_csv(
    license_url,
    low_memory=False
)

print("Shape:", business_licenses.shape)

display(business_licenses.head())

print("\nColumn types:")
print(business_licenses.dtypes)

Shape: (50000, 37)

,id,license_id,account_number,site_number,legal_name,doing_business_as_name,address,city,state,zip_code,ward,precinct,ward_precinct,police_district,community_area,community_area_name,neighborhood,license_code,license_description,business_activity_id,business_activity,license_number,application_type,application_created_date,application_requirements_complete,payment_date,conditional_approval,license_start_date,expiration_date,license_approved_for_issuance,date_issued,license_status,license_status_change_date,ssa,latitude,longitude,location
0,2390791-20260916,3092560,294123,2,"ARCHIPELAGO SECURITIES, L.L.C.","ARCHIPELAGO SECURITIES, L.L.C.",353 N CLARK ST 31,CHICAGO,IL,60654,42.0,32.0,42-32,18.0,8.0,NEAR NORTH SIDE,RIVER NORTH,1010,Limited Business License,708,Miscellaneous Commercial Services,2390791,RENEW,NaN,2026-07-15T00:00:00.000,2026-08-18T00:00:00.000,N,2026-09-16T00:00:00.000,2028-09-15T00:00:00.000,2026-08-18T00:00:00.000,2026-09-25T00:00:00.000,AAI,NaN,NaN,41.888962,-87.630907,"\n, \n(41.88896195675864, -87.63090677238614)"
1,3095727-20260925,3095727,529382,1,BIBI ENTERPRISE USA INC.,ZEENAT EMPORIUM,6348 N CAMPBELL AVE,CHICAGO,IL,60659,50.0,30.0,50-30,24.0,2.0,WEST RIDGE,WEST RIDGE,1010,Limited Business License,904,Retail Sales of General Merchandise,3095727,ISSUE,2026-07-23T00:00:00.000,2026-08-11T00:00:00.000,2026-09-25T00:00:00.000,N,2026-09-25T00:00:00.000,2028-10-15T00:00:00.000,2026-09-25T00:00:00.000,2026-09-25T00:00:00.000,AAI,NaN,43.0,41.997315,-87.692459,"\n, \n(41.997314846509255, -87.69245944093181)"
2,2863556-20261116,3102529,421444,2,"7140 DORCHESTER PROPERTIES, LLC",EDEN SOUTH SHORE,7156 S DORCHESTER AVE 1-4,CHICAGO,IL,60619,8.0,1.0,8-1,3.0,43.0,SOUTH SHORE,SOUTH SHORE,4404,Regulated Business License,236,Assisted Living Establishment,2863556,RENEW,NaN,2026-09-15T00:00:00.000,2026-09-24T00:00:00.000,N,2026-11-16T00:00:00.000,2028-11-15T00:00:00.000,2026-09-24T00:00:00.000,2026-09-25T00:00:00.000,AAI,NaN,NaN,41.764303,-87.591096,"\n, \n(41.76430277851535, -87.59109571691616)"
3,2431903-20251216,3054313,401997,1,OAATO FOODS INC.,OAATO FOODS INC.,7118 N CLARK ST GROUND,CHICAGO,IL,60626,49.0,3.0,49-3,24.0,1.0,ROGERS PARK,ROGERS PARK,1006,Retail Food Establishment,781,Sale of Food Prepared Onsite With Dining Area,2431903,RENEW,NaN,2025-10-15T00:00:00.000,2026-09-25T00:00:00.000,N,2025-12-16T00:00:00.000,2027-12-15T00:00:00.000,2026-09-25T00:00:00.000,2026-09-25T00:00:00.000,AAI,NaN,24.0,42.012010,-87.674686,"\n, \n(42.012010233551145, -87.6746862866216)"
4,3104325-20260925,3104325,508265,3,KTM KITCHEN LLC,THE KTM KITCHEN,120 W MADISON ST,CHICAGO,IL,60602,34.0,9.0,34-9,1.0,32.0,LOOP,LOOP,1329,Special Event Food,942,5 Day Single Event - Special Event Food,3104325,ISSUE,2026-09-25T00:00:00.000,2026-09-25T00:00:00.000,2026-09-25T00:00:00.000,N,2026-09-25T00:00:00.000,2026-09-28T00:00:00.000,2026-09-25T00:00:00.000,2026-09-25T00:00:00.000,AAI,NaN,NaN,41.882081,-87.631513,"\n, \n(41.882081136557176, -87.6315134139163)"

Column types:
id                                    object
license_id                             int64
account_number                         int64
site_number                            int64
legal_name                            object
doing_business_as_name                object
address                               object
city                                  object
state                                 object
zip_code                              object
ward                                 float64
precinct                             float64
ward_precinct                         object
police_district                      float64
community_area                       float64
community_area_name                   object
neighborhood                          object
license_code                           int64
license_description                   object
business_activity_id                  object
business_activity                     object
license_number                         int64
application_type                      object
application_created_date              object
application_requirements_complete     object
payment_date                          object
conditional_approval                  object
license_start_date                    object
expiration_date                       object
license_approved_for_issuance         object
date_issued                           object
license_status                        object
license_status_change_date            object
ssa                                  float64
latitude                             float64
longitude                            float64
location                              object
dtype: object

In [34]:
business_licenses.columns.tolist()

['id',
 'license_id',
 'account_number',
 'site_number',
 'legal_name',
 'doing_business_as_name',
 'address',
 'city',
 'state',
 'zip_code',
 'ward',
 'precinct',
 'ward_precinct',
 'police_district',
 'community_area',
 'community_area_name',
 'neighborhood',
 'license_code',
 'license_description',
 'business_activity_id',
 'business_activity',
 'license_number',
 'application_type',
 'application_created_date',
 'application_requirements_complete',
 'payment_date',
 'conditional_approval',
 'license_start_date',
 'expiration_date',
 'license_approved_for_issuance',
 'date_issued',
 'license_status',
 'license_status_change_date',
 'ssa',
 'latitude',
 'longitude',
 'location']

In [35]:
def summarize_dataset(df, name):
    print("=" * 60)
    print(name)
    print("=" * 60)

    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])

    print("\nColumn names:")
    print(df.columns.tolist())

    print("\nData types:")
    print(df.dtypes)

    print("\nFirst 5 rows:")
    display(df.head())

In [36]:
summarize_dataset(
    food_inspections,
    "Chicago Food Inspections"
)

============================================================
Chicago Food Inspections
============================================================
Rows: 50000
Columns: 17

Column names:
['inspection_id', 'dba_name', 'aka_name', 'license_', 'facility_type', 'risk', 'address', 'city', 'state', 'zip', 'inspection_date', 'inspection_type', 'results', 'violations', 'latitude', 'longitude', 'location']

Data types:
inspection_id        int64
dba_name            object
aka_name            object
license_           float64
facility_type       object
risk                object
address             object
city                object
state               object
zip                float64
inspection_date     object
inspection_type     object
results             object
violations          object
latitude           float64
longitude          float64
location            object
dtype: object

First 5 rows:

,inspection_id,dba_name,aka_name,license_,facility_type,risk,address,city,state,zip,inspection_date,inspection_type,results,violations,latitude,longitude,location
0,2643334,KAROLINKA CLUB,KAROLINKA CLUB,1645224.0,Restaurant,Risk 1 (High),6102 S CENTRAL AVE,CHICAGO,IL,60638.0,2026-09-25T00:00:00.000,Non-Inspection,No Entry,NaN,41.781570,-87.762013,"\n, \n(41.78156970293239, -87.76201319891189)"
1,2643326,LITTLE TYKES II DAYCARE INC,LITTLE TYKES II DAYCARE INC,2215776.0,Daycare Above and Under 2 Years,Risk 1 (High),1723 W 35TH ST,CHICAGO,IL,60609.0,2026-09-25T00:00:00.000,Canvass,Pass,"48. WAREWASHING FACILITIES: INSTALLED, MAINTAI...",41.830353,-87.668943,"\n, \n(41.83035319104033, -87.66894292273008)"
2,2643349,BUNDOO KHAN,BUNDOO KHAN,2802568.0,Restaurant,Risk 1 (High),2537-2539 W DEVON AVE,CHICAGO,IL,60659.0,2026-09-25T00:00:00.000,Complaint Re-Inspection,Fail,"28. TOXIC SUBSTANCES PROPERLY IDENTIFIED, STOR...",41.997554,-87.693770,"\n, \n(41.99755417277127, -87.69377017915909)"
3,2643342,CHICAGO PIT STOP BBQ,CHICAGO PIT STOP BBQ,1696182.0,Restaurant,Risk 1 (High),6514 S WESTERN AVE,CHICAGO,IL,60636.0,2026-09-25T00:00:00.000,Complaint Re-Inspection,Pass,NaN,41.775112,-87.683679,"\n, \n(41.77511152013113, -87.68367904074279)"
4,2643336,BACCI CAFE AND PIZZERIA ON MILWAUKEE AVE. INC.,LEGACY PIZZA/BACCI CAFE AND PIZZERIA,1444299.0,Restaurant,Risk 1 (High),4367 N MILWAUKEE AVE,CHICAGO,IL,60641.0,2026-09-25T00:00:00.000,Complaint Re-Inspection,Pass w/ Conditions,63. REMOVAL OF SUSPENSION SIGN - Comments: 'LI...,41.960551,-87.754231,"\n, \n(41.96055088007665, -87.7542307472157)"

In [37]:
summarize_dataset(
    business_licenses,
    "Chicago Business Licenses"
)

============================================================
Chicago Business Licenses
============================================================
Rows: 50000
Columns: 37

Column names:
['id', 'license_id', 'account_number', 'site_number', 'legal_name', 'doing_business_as_name', 'address', 'city', 'state', 'zip_code', 'ward', 'precinct', 'ward_precinct', 'police_district', 'community_area', 'community_area_name', 'neighborhood', 'license_code', 'license_description', 'business_activity_id', 'business_activity', 'license_number', 'application_type', 'application_created_date', 'application_requirements_complete', 'payment_date', 'conditional_approval', 'license_start_date', 'expiration_date', 'license_approved_for_issuance', 'date_issued', 'license_status', 'license_status_change_date', 'ssa', 'latitude', 'longitude', 'location']

Data types:
id                                    object
license_id                             int64
account_number                         int64
site_number                            int64
legal_name                            object
doing_business_as_name                object
address                               object
city                                  object
state                                 object
zip_code                              object
ward                                 float64
precinct                             float64
ward_precinct                         object
police_district                      float64
community_area                       float64
community_area_name                   object
neighborhood                          object
license_code                           int64
license_description                   object
business_activity_id                  object
business_activity                     object
license_number                         int64
application_type                      object
application_created_date              object
application_requirements_complete     object
payment_date                          object
conditional_approval                  object
license_start_date                    object
expiration_date                       object
license_approved_for_issuance         object
date_issued                           object
license_status                        object
license_status_change_date            object
ssa                                  float64
latitude                             float64
longitude                            float64
location                              object
dtype: object

First 5 rows:

,id,license_id,account_number,site_number,legal_name,doing_business_as_name,address,city,state,zip_code,ward,precinct,ward_precinct,police_district,community_area,community_area_name,neighborhood,license_code,license_description,business_activity_id,business_activity,license_number,application_type,application_created_date,application_requirements_complete,payment_date,conditional_approval,license_start_date,expiration_date,license_approved_for_issuance,date_issued,license_status,license_status_change_date,ssa,latitude,longitude,location
0,2390791-20260916,3092560,294123,2,"ARCHIPELAGO SECURITIES, L.L.C.","ARCHIPELAGO SECURITIES, L.L.C.",353 N CLARK ST 31,CHICAGO,IL,60654,42.0,32.0,42-32,18.0,8.0,NEAR NORTH SIDE,RIVER NORTH,1010,Limited Business License,708,Miscellaneous Commercial Services,2390791,RENEW,NaN,2026-07-15T00:00:00.000,2026-08-18T00:00:00.000,N,2026-09-16T00:00:00.000,2028-09-15T00:00:00.000,2026-08-18T00:00:00.000,2026-09-25T00:00:00.000,AAI,NaN,NaN,41.888962,-87.630907,"\n, \n(41.88896195675864, -87.63090677238614)"
1,3095727-20260925,3095727,529382,1,BIBI ENTERPRISE USA INC.,ZEENAT EMPORIUM,6348 N CAMPBELL AVE,CHICAGO,IL,60659,50.0,30.0,50-30,24.0,2.0,WEST RIDGE,WEST RIDGE,1010,Limited Business License,904,Retail Sales of General Merchandise,3095727,ISSUE,2026-07-23T00:00:00.000,2026-08-11T00:00:00.000,2026-09-25T00:00:00.000,N,2026-09-25T00:00:00.000,2028-10-15T00:00:00.000,2026-09-25T00:00:00.000,2026-09-25T00:00:00.000,AAI,NaN,43.0,41.997315,-87.692459,"\n, \n(41.997314846509255, -87.69245944093181)"
2,2863556-20261116,3102529,421444,2,"7140 DORCHESTER PROPERTIES, LLC",EDEN SOUTH SHORE,7156 S DORCHESTER AVE 1-4,CHICAGO,IL,60619,8.0,1.0,8-1,3.0,43.0,SOUTH SHORE,SOUTH SHORE,4404,Regulated Business License,236,Assisted Living Establishment,2863556,RENEW,NaN,2026-09-15T00:00:00.000,2026-09-24T00:00:00.000,N,2026-11-16T00:00:00.000,2028-11-15T00:00:00.000,2026-09-24T00:00:00.000,2026-09-25T00:00:00.000,AAI,NaN,NaN,41.764303,-87.591096,"\n, \n(41.76430277851535, -87.59109571691616)"
3,2431903-20251216,3054313,401997,1,OAATO FOODS INC.,OAATO FOODS INC.,7118 N CLARK ST GROUND,CHICAGO,IL,60626,49.0,3.0,49-3,24.0,1.0,ROGERS PARK,ROGERS PARK,1006,Retail Food Establishment,781,Sale of Food Prepared Onsite With Dining Area,2431903,RENEW,NaN,2025-10-15T00:00:00.000,2026-09-25T00:00:00.000,N,2025-12-16T00:00:00.000,2027-12-15T00:00:00.000,2026-09-25T00:00:00.000,2026-09-25T00:00:00.000,AAI,NaN,24.0,42.012010,-87.674686,"\n, \n(42.012010233551145, -87.6746862866216)"
4,3104325-20260925,3104325,508265,3,KTM KITCHEN LLC,THE KTM KITCHEN,120 W MADISON ST,CHICAGO,IL,60602,34.0,9.0,34-9,1.0,32.0,LOOP,LOOP,1329,Special Event Food,942,5 Day Single Event - Special Event Food,3104325,ISSUE,2026-09-25T00:00:00.000,2026-09-25T00:00:00.000,2026-09-25T00:00:00.000,N,2026-09-25T00:00:00.000,2026-09-28T00:00:00.000,2026-09-25T00:00:00.000,2026-09-25T00:00:00.000,AAI,NaN,NaN,41.882081,-87.631513,"\n, \n(41.882081136557176, -87.6315134139163)"

Google Local Reviews

In [38]:
# Google local reviews
google_metadata = pd.read_json(
    "data/meta-Illinois.json.gz",
    lines=True,
    compression="gzip"
)

print("Shape:", google_metadata.shape)

display(google_metadata.head())

print(google_metadata.dtypes)

Shape: (179205, 15)

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
0,The Toy House,"The Toy House, 10 E Main St #105, East Dundee,...",0x880f0f1b32155555:0x8347e0c971acb955,None,42.098159,-88.275237,[Toy store],4.9,17,None,"[[Thursday, 10AM–8PM], [Friday, 10AM–8PM], [Sa...",{'Accessibility': ['Wheelchair accessible entr...,Permanently closed,"[0x880f72a26e93c371:0xed11dd45ac49ed11, 0x880f...",https://www.google.com/maps/place//data=!4m2!3...
1,ROYAL LIQUOR,"ROYAL LIQUOR, 26W211 Geneva Rd, Wheaton, IL 60187",0x880e5523024703c1:0xb93a8ccb6918d616,None,41.887341,-88.136456,[Liquor store],3.6,8,None,"[[Thursday, 10AM–10PM], [Friday, 10AM–10:30PM]...","{'Service options': ['In-store shopping', 'Del...",Open ⋅ Closes 10PM,"[0x880e55410d7a8187:0x9863102d1658ecf2, 0x880e...",https://www.google.com/maps/place//data=!4m2!3...
2,Carmi Taekwondo Center,"Carmi Taekwondo Center, 106 E Main St, Carmi, ...",0x8871a9d31e1aeeb1:0x79cee38dfa5a74c9,None,38.089658,-88.160471,[Taekwondo school],5.0,3,None,"[[Thursday, 4–9PM], [Friday, Closed], [Saturda...",{'Accessibility': ['Wheelchair accessible entr...,Closed ⋅ Opens 4PM,"[0x8871a82cca0a79a7:0x3294bb72dd9c1df6, 0x8871...",https://www.google.com/maps/place//data=!4m2!3...
3,Neikirk Alternative Heating,"Neikirk Alternative Heating, 8527 N 1250 Blvd,...",0x8871ec92b7b69123:0x5afcdb82d81c81ae,None,38.401572,-87.826757,[General contractor],3.0,1,None,None,None,None,"[0x8871ee91a3958faf:0x861162a80fe264d, 0x8871e...",https://www.google.com/maps/place//data=!4m2!3...
4,Barry Haggard Tank Truck Services,"Barry Haggard Tank Truck Services, 1309 Poplar...",0x8871ee802fd26b3f:0x9d664ba7e6ff48d8,None,38.419776,-87.775755,[Trucking company],5.0,1,None,None,None,None,"[0x8871f0bdfaf8239b:0xbdd9fc431aaa3b64, 0x8871...",https://www.google.com/maps/place//data=!4m2!3...

name                 object
address              object
gmap_id              object
description          object
latitude            float64
longitude           float64
category             object
avg_rating          float64
num_of_reviews        int64
price                object
hours                object
MISC                 object
state                object
relative_results     object
url                  object
dtype: object

In [39]:
google_metadata["category"].head()

0             [Toy store]
1          [Liquor store]
2      [Taekwondo school]
3    [General contractor]
4      [Trucking company]
Name: category, dtype: object

In [40]:
google_restaurants = google_metadata[
    google_metadata["category"].apply(
        lambda x: isinstance(x, list)
        and any(
            "restaurant" in str(category).lower()
            for category in x
        )
    )
].copy()

print("All Illinois businesses:", google_metadata.shape)
print("Illinois restaurants:", google_restaurants.shape)

display(google_restaurants.head())

All Illinois businesses: (179205, 15)
Illinois restaurants: (28809, 15)

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,MISC,state,relative_results,url
65,"KHANA KHAZANA ""A Traditional Indian Cafe""","KHANA KHAZANA ""A Traditional Indian Cafe"", 100...",0x880f2bedf0364aa9:0x2cfb9ba857d919d6,None,41.931504,-88.771155,"[Indian restaurant, Cafeteria]",4.1,26,$,"[[Thursday, 11AM–8:30PM], [Friday, 11AM–8:30PM...","{'Service options': ['No-contact delivery', 'D...",Closed ⋅ Opens 11AM,"[0x880f2abfd7f80ed1:0x776c89d48032c711, 0x880f...",https://www.google.com/maps/place//data=!4m2!3...
99,Aria,"Aria, 200 N Columbus Dr, Chicago, IL 60601",0x880e2ca867ab1e83:0x2d74d09c9e2daec6,This splashy L-shaped space in the Fairmont Ho...,41.886012,-87.620938,"[Restaurant, American restaurant, Bar]",3.9,18,None,None,"{'Service options': ['Delivery'], 'Highlights'...",None,"[0x880e2ca46b2bafe5:0x1d0780a2c49db10, 0x880fd...",https://www.google.com/maps/place//data=!4m2!3...
100,Rosebud Trattoria,"Rosebud Trattoria, 445 N Dearborn St, Chicago,...",0x880e2cb219200cab:0xa7869caab226ce4,None,41.890598,-87.629384,"[Italian restaurant, Restaurant]",4.8,8,$$$,None,"{'Service options': ['Delivery'], 'Highlights'...",None,None,https://www.google.com/maps/place//data=!4m2!3...
114,It's Just Wings,"It's Just Wings, 3795 E Main St, St. Charles, ...",0x880f0301bb6f52f3:0xba72c296dcfa82ba,None,41.920542,-88.268611,"[Chicken wings restaurant, Chicken restaurant,...",3.5,2,$$,"[[Wednesday, 11AM–10PM], [Thursday, 11AM–10PM]...","{'Service options': ['Curbside pickup', 'No-co...",Closes soon ⋅ 10PM ⋅ Opens 11AM Thu,None,https://www.google.com/maps/place//data=!4m2!3...
117,Stop and Roll,"Stop and Roll, 210 S 5th St, Springfield, IL 6...",0x887539c6afb2ce09:0xc86d7821fefef0a1,None,39.800153,-89.649177,"[Sushi restaurant, Ramen restaurant]",4.9,38,$$,"[[Wednesday, 11AM–2PM], [Thursday, 11AM–2PM], ...",{'Service options': ['Delivery']},Permanently closed,[0x887539c1855e0609:0xf23f8fe2cd525e38],https://www.google.com/maps/place//data=!4m2!3...

In [41]:
google_reviews = pd.read_json(
    "data/review-Illinois.json.gz",
    lines=True,
    compression="gzip",
    nrows=100000
)

print("Shape:", google_reviews.shape)

display(google_reviews.head())

print(google_reviews.dtypes)

Shape: (100000, 8)

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.094426e+20,Jim LeBurkien,1571842572977,5,Great selection of used and collectible toys. ...,None,None,0x880f0f1b32155555:0x8347e0c971acb955
1,1.148153e+20,William Cummins,1530143693720,5,Deege and Carlos are two of the nicest people ...,None,None,0x880f0f1b32155555:0x8347e0c971acb955
2,1.178943e+20,Christopher Figueroa,1530386860695,5,The atmosphere great! Loved the place and the ...,None,None,0x880f0f1b32155555:0x8347e0c971acb955
3,1.078095e+20,Chacho Rico,1565902155245,5,Always friendly and flexible on prices a great...,None,None,0x880f0f1b32155555:0x8347e0c971acb955
4,1.050784e+20,Dr. Catherine Oliver,1565211242642,5,Very nice staff and reasonable prices.,None,None,0x880f0f1b32155555:0x8347e0c971acb955

user_id    float64
name        object
time         int64
rating       int64
text        object
pics        object
resp        object
gmap_id     object
dtype: object

In [42]:
google_review_columns = [
    "gmap_id",
    "rating",
    "text",
    "time",
    "resp"
]

display(google_reviews[google_review_columns].head())

,gmap_id,rating,text,time,resp
0,0x880f0f1b32155555:0x8347e0c971acb955,5,Great selection of used and collectible toys. ...,1571842572977,None
1,0x880f0f1b32155555:0x8347e0c971acb955,5,Deege and Carlos are two of the nicest people ...,1530143693720,None
2,0x880f0f1b32155555:0x8347e0c971acb955,5,The atmosphere great! Loved the place and the ...,1530386860695,None
3,0x880f0f1b32155555:0x8347e0c971acb955,5,Always friendly and flexible on prices a great...,1565902155245,None
4,0x880f0f1b32155555:0x8347e0c971acb955,5,Very nice staff and reasonable prices.,1565211242642,None

Yelp

In [43]:
yelp_business = pd.read_json(
    "data/yelp_academic_dataset_business.json",
    lines=True
)

print("Shape:", yelp_business.shape)

display(yelp_business.head())

print(yelp_business.dtypes)

Shape: (150346, 14)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."

business_id      object
name             object
address          object
city             object
state            object
postal_code      object
latitude        float64
longitude       float64
stars           float64
review_count      int64
is_open           int64
attributes       object
categories       object
hours            object
dtype: object

In [44]:
yelp_reviews = pd.read_json(
    "data/yelp_academic_dataset_review.json",
    lines=True,
    nrows=100000
)

print("Shape:", yelp_reviews.shape)

display(yelp_reviews.head())

print(yelp_reviews.dtypes)

Shape: (100000, 9)

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4,1,0,1,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15

review_id              object
user_id                object
business_id            object
stars                   int64
useful                  int64
funny                   int64
cool                    int64
text                   object
date           datetime64[ns]
dtype: object

In [45]:
# -------------------------------------------
# Coverage / date-range summary
# -------------------------------------------

# Chicago Food Inspections
food_inspections["inspection_date"] = pd.to_datetime(
    food_inspections["inspection_date"],
    errors="coerce"
)

print("Chicago Food Inspections")
print(
    "Date range:",
    food_inspections["inspection_date"].min(),
    "to",
    food_inspections["inspection_date"].max()
)
print(
    "Cities:",
    food_inspections["city"].dropna().unique()[:10]
)


# Chicago Business Licenses
business_licenses["license_start_date"] = pd.to_datetime(
    business_licenses["license_start_date"],
    errors="coerce"
)

print("\nChicago Business Licenses")
print(
    "License start date range:",
    business_licenses["license_start_date"].min(),
    "to",
    business_licenses["license_start_date"].max()
)
print(
    "Cities:",
    business_licenses["city"].dropna().unique()[:10]
)


# Google Local Reviews
google_reviews["review_date"] = pd.to_datetime(
    google_reviews["time"],
    unit="ms",
    errors="coerce"
)

print("\nGoogle Local Reviews sample")
print(
    "Review date range:",
    google_reviews["review_date"].min(),
    "to",
    google_reviews["review_date"].max()
)


# Yelp Reviews
print("\nYelp Reviews sample")
print(
    "Review date range:",
    yelp_reviews["date"].min(),
    "to",
    yelp_reviews["date"].max()
)

print(
    "Yelp states:",
    sorted(yelp_business["state"].dropna().unique())
)

Chicago Food Inspections
Date range: 2024-01-09 00:00:00 to 2026-09-25 00:00:00
Cities: ['CHICAGO' 'Chicago' 'chicago' 'CAROL STREAM' 'MAPLE PARK' 'CHICAGO.'
 'WASHINGTON' 'ZION' 'SCHAUMBURG' 'EVANSTON']

Chicago Business Licenses
License start date range: 2004-02-16 00:00:00 to 2028-07-16 00:00:00
Cities: ['CHICAGO' 'LEMONT' 'WORTH' 'TINLEY PARK' 'SPRINGFIELD' 'INDIA' 'OAKLAND'
 'BURBANK' 'FRANKLIN PARK' 'ADDISON']

Google Local Reviews sample
Review date range: 2008-01-29 00:00:00 to 2021-09-08 23:17:20.232000

Yelp Reviews sample
Review date range: 2005-03-01 17:47:15 to 2018-10-04 18:22:35
Yelp states: ['AB', 'AZ', 'CA', 'CO', 'DE', 'FL', 'HI', 'ID', 'IL', 'IN', 'LA', 'MA', 'MI', 'MO', 'MT', 'NC', 'NJ', 'NV', 'PA', 'SD', 'TN', 'TX', 'UT', 'VI', 'VT', 'WA', 'XMS']